### ISSUE TITLE
ILIAS + LfMainMenu

### ISSUE THREAD

**Issue by AKals** [leifos-gmbh/LfMainMenu#1]
Nach dem entpacken der Zip, wird Das Plugin im ILIAS angezeigt.
Beim klick auf Aktualisieren wird folgender Fehler angezeigt:

Fatal error: Call to a member function update() on a non-object in /var/www/html/ILIAS-5.0.4/Services/Component/classes/class.ilObjComponentSettingsGUI.php on line 520

Ich habe im Internet den selben Fehler gefunden:
http://stackoverflow.com/questions/29494812/fatal-error-call-to-a-member-function-update-on-null?answertab=votes#tab-top

aber auch den Ordner "SystemNotifications-master" kann ich nirgends finden.

Ich hatte mich schon auf eine einfach Installation gefreut (Einfügen, aktivieren, fertig).

Ich würde diese Plugin sehr gerne nutzen. Aber wie?

Beste Grüße 

Andreas Kals

**Comment by alex40724** [comment]
In welchem Verzeichnis ist das Plugin innerhalb von Customizing denn gelandet?
Es sollte
Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/LfMainMenu
sein (Groß/Kleinschreibung unbedingt beachten)

**Comment by AKals** [comment]
Es liegt in folgendem Verzeichnis:
Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/LfMainMenu-5.0.2

**Comment by alex40724** [comment]
Dann ist das die Ursache, bitte einfach das Verzeichnis umbenennen.

**Comment by AKals** [comment]
Es klappt..... vielen Dank für die tolle Hilfe.... *peinlich*
