### ISSUE TITLE
LfMainMenu non-object

### ISSUE THREAD

**Issue by fgalbarz** [leifos-gmbh/LfMainMenu#2]
Hallo.

Vor dem Update unserer Lernplattform von 4.X auf 5.X haben wir in einer Testumgebung (ILIAS 5.0.4) auf einem anderen Server viele Neuerungen ausprobiert, u.a. auch das LfMainMenu-Plug-in. Dabei kam es zu einem recht schwerwiegendem Problem (ich versuche es aus der Erinnerung so gut wie möglich zu beschreiben):
Ich erstellte neben den vorkonfigurierten Menupunkten "Magazin" und "Persönlicher Schreibtisch" auch einen individuellen, bei dem ich auch einen Untermenupunkt anlegte. Wahrscheinlich habe ich dort als Objekt-ID eine nicht vergebene eingegeben, denn nachdem ich die Einstellungen speicherte, zeigte der Browser nur eine leere Seite (wie about:blank). Seitdem konnte ich mich nicht mehr einloggen, auch nicht mit anderen Accounts. Unser technischer Dienstleister konnte das Plug-in deaktivieren und mir die Fehlermeldung mitteilen, die mir selbst im Browser nicht angezeigt wurde:

"Call to a member function checkAccess() on a non-object in /var/www/ilias/htdocs/ilias-5.0.4/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/LfMainMenu/classes/class.ilLfMainMenuUIHookGUI.php on line 363"

Wir werden das Plug-in wahrscheinlich erst mal nicht auf unserem Live-System einsetzen, da die Gefahr besteht, dass ein solcher Eingabefehler wieder zu schwerwiegenden Problemen führt. Vielleicht gibt es ja eine Möglichkeit, eine Validierung einzubauen, sodass man eine Warnung bekommt, wenn man falsche Werte eingibt. (Oder vielleicht habe ich mich auch einfach nur beim wilden Testen zu blöd angestellt...)

Danke und beste Grüße
Florian Galbarz

**Comment by alex40724** [comment]
Fixed in master.
